name: sdl_mobile
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  auto_route: ^7.8.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  copy_with_extension: ^5.0.4
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  # device_info_plus: ^8.0.0
  device_preview: ^1.1.0
  dio: ^4.0.6
  dio_cache_interceptor: ^3.4.0
  dio_http_cache_lts: ^0.4.1
  easy_localization: any
  equatable: ^2.0.3
  event_bus: ^2.0.0
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_image_compress: ^2.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^15.1.1
  flutter_native_splash: ^2.2.15
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.5.3+2
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.7
  flutter_widget_from_html: ^0.14.4+1
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.3.0
  internet_file: ^1.2.0
  json_annotation: ^4.5.0
  logger: ^2.0.1
  lottie: ^2.5.0
  path_provider: ^2.0.11
  permission_handler: ^10.3.0
  photo_view: ^0.14.0
  retrofit: ^3.3.1
  rxdart: ^0.27.7
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  top_snackbar_flutter: ^3.1.0
  url_launcher: ^6.1.12

dependency_overrides: null

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  copy_with_extension_gen: ^5.0.4
  flutter_gen_runner: ^5.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  injectable_generator: any
  json_serializable: ^6.2.0
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/svg/
    - assets/fonts/
    - assets/json/
    - assets/env/
    - assets/lotties/
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-SemiBold.ttf
          weight: 600
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    # lottie: true

  assets:
    enable: true
    package_parameter_enabled: false

#  colors:
#    inputs:
#      - assets/color/colors.xml
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: null
